<<<<<<< HEAD
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'weather-app'
    static_configs:
      - targets: ['weather-app:8080']
=======
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'weather-app'
    static_configs:
      - targets: ['weather-app:8080']
>>>>>>> 428f5cd2f762435819e1f11314a19742522374ff
